name: Docker Build

on:
  workflow_run:
    workflows: ["Build with Gradle"]
    types:
      - completed

jobs:
  docker-build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag myapp:latest

      - name: Run Docker Image
        run: docker run --rm -d -p 8080:8080 myapp:latest
